window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.buildings = {
  townHall: {
    name: "Town Hall",
    role: "population_core",
    description: "The heart of your settlement and its population limit.",
    info: "Population cap, growth, and village rank",
    unlock: "start",
    visibility: { type: "always" },
    cost: { wood: 64, stone: 42, food: 20 },
    slots: 0,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 30,
    notes: ["Population cap", "Growth support", "Village rank", "Main progression spine"],
  },
  farm: {
    name: "Farm",
    role: "food_production",
    description: "Your main food estate.",
    info: "Food and Farmer capacity",
    unlock: "start",
    visibility: { type: "always" },
    cost: { wood: 20, stone: 10, food: 8 },
    output: { food: 0.42 },
    slots: 4,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Food output", "Farmer capacity", "Base output increased in early-game balance pass"],
  },
  lumberMill: {
    name: "Lumber Mill",
    role: "wood_production",
    description: "Your timber production hub.",
    info: "Wood and Woodcutter capacity",
    unlock: "wood >= 8 or already built",
    visibility: { type: "resourceCurrentAtLeastOrBuilt", resource: "wood", amount: 8 },
    cost: { wood: 28, stone: 14, food: 10 },
    output: { wood: 0.22 },
    slots: 3,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Wood output", "Woodcutter capacity"],
  },
  quarry: {
    name: "Quarry",
    role: "stone_production",
    description: "Your main stone extraction site.",
    info: "Stone and Quarry Miner capacity",
    unlock: "farm built or already built",
    visibility: { type: "buildingBuiltOrBuilt", building: "farm" },
    cost: { wood: 30, stone: 18, food: 12 },
    output: { stone: 0.18 },
    slots: 3,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Stone output", "Quarry Miner capacity"],
  },
  workshop: {
    name: "Workshop",
    role: "production_support",
    description: "Organizes tools and craft.",
    info: "Improves production efficiency and upgrades",
    unlock: "Craftsmanship",
    visibility: { type: "techOrBuilt", tech: "craftsmanship" },
    cost: { wood: 32, stone: 18, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Building base output bonus"],
  },
  scribeHall: {
    name: "Scribe Hall",
    role: "knowledge_production",
    description: "A quiet place where Scholars turn records into Knowledge.",
    info: "Knowledge and Scholar capacity after Gold Mining",
    unlock: "Gold Mining + Town Hall Lv4",
    visibility: { type: "techOrBuilt", tech: "goldMining" },
    cost: { wood: 28, stone: 18, food: 10 },
    output: { knowledge: 0.06 },
    slots: 1,
    upkeepBase: 0.03,
    unique: true,
    maxLevel: 50,
    townHallLevel: 4,
    notes: ["Knowledge output", "Scholar capacity", "Now appears only after Gold Mining is online"],
  },
  barracks: {
    name: "Barracks",
    role: "military_unlock",
    description: "Unlocks Soldiers and Guards.",
    info: "Military training and village defense",
    unlock: "quarry built or already built",
    visibility: { type: "buildingBuiltOrBuilt", building: "quarry" },
    townHallLevel: 4,
    cost: { wood: 36, stone: 24, food: 16 },
    slots: 0,
    upkeepBase: 0.08,
    unique: true,
    maxLevel: 50,
    notes: ["Soldiers", "Guards", "Defense layer"],
  },
  warehouse: {
    name: "Warehouse",
    role: "storage_support",
    description: "A broad storeyard for village stockpiles.",
    info: "Large global storage boost",
    unlock: "Storehouse Planning",
    visibility: { type: "techOrBuilt", tech: "storehousePlanning" },
    townHallLevel: 2,
    cost: { wood: 40, stone: 26, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Global storage boost", "Uses the stronger warehouseBonus curve", "Available earlier to prevent storage deadlocks", "Now scales harder so Town Hall upgrades do not outrun storage again"],
  },
  goldMine: {
    name: "Gold Mine",
    role: "gold_production",
    description: "A rich mine for late trade and research.",
    info: "Gold and Gold Miner capacity",
    unlock: "Gold Mining",
    visibility: { type: "techOrBuilt", tech: "goldMining" },
    townHallLevel: 5,
    cost: { wood: 52, stone: 38, food: 24 },
    output: { gold: 0.13 },
    slots: 2,
    upkeepBase: 0.07,
    unique: true,
    maxLevel: 50,
    notes: ["Gold output", "Gold Miner capacity"],
  },
  vineyard: {
    name: "Vineyard",
    role: "luxury_production",
    description: "Terraced vines for later luxuries.",
    info: "Wine production and happiness support",
    unlock: "Viticulture",
    visibility: { type: "techOrBuilt", tech: "viticulture" },
    townHallLevel: 10,
    cost: { wood: 42, stone: 22, food: 24 },
    output: { wine: 0.14 },
    slots: 2,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Wine output", "Vinekeeper capacity", "Supports Happiness"],
  },
  winery: {
    name: "Winery",
    role: "luxury_refinement",
    description: "Presses, stores and improves local wine.",
    info: "Refined wine output and happiness support",
    unlock: "Vintage Press",
    visibility: { type: "techOrBuilt", tech: "vintagePress" },
    townHallLevel: 12,
    cost: { wood: 56, stone: 30, food: 22 },
    slots: 2,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Wine throughput", "Vintner capacity"],
  },
  oreMine: {
    name: "Ore Pit",
    role: "ore_production",
    description: "A deep excavation for raw ore.",
    info: "Ore extraction for later metalwork",
    unlock: "Ore Extraction",
    visibility: { type: "techOrBuilt", tech: "oreExtraction" },
    townHallLevel: 10,
    cost: { wood: 58, stone: 42, food: 28 },
    slots: 2,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 50,
    notes: ["Ore output", "Ore Miner capacity", "Brought forward to avoid Town Hall progression deadlocks"],
  },
  smelter: {
    name: "Smelter",
    role: "metal_production",
    description: "Refines ore into usable metal.",
    info: "Metal production for tools and arms",
    unlock: "Smithing",
    visibility: { type: "techOrBuilt", tech: "smithing" },
    townHallLevel: 14,
    cost: { wood: 64, stone: 46, food: 26, gold: 2 },
    slots: 2,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 50,
    notes: ["Metal output", "Consumes Ore", "Smelter capacity"],
  },
  tavern: {
    name: "Tavern",
    role: "happiness_support",
    description: "Keeps spirits high with warm rooms and wine.",
    info: "Happiness and growth support through wine",
    unlock: "Tavern Culture",
    visibility: { type: "techOrBuilt", tech: "tavernCulture" },
    townHallLevel: 15,
    cost: { wood: 60, stone: 34, food: 26, gold: 2 },
    slots: 2,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Happiness support", "Consumes Wine", "Innkeeper capacity"],
  },
};

if (typeof module !== "undefined") {
  module.exports = { buildings: window.CoinvaleReference.buildings };
}
