window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.buildings = {
  townHall: {
    name: "Town Hall",
    role: "population_core",
    description: "The heart of your settlement and its population limit.",
    unlock: "start",
    cost: { wood: 64, stone: 42, food: 20 },
    slots: 0,
    upkeepBase: 0.06,
    unique: true,
    notes: ["Population cap", "Growth support", "Village rank"],
  },
  farm: {
    name: "Farm",
    role: "food_production",
    description: "Base Food and Farmer slots.",
    unlock: "start",
    cost: { wood: 20, stone: 10, food: 8 },
    slots: 2,
    upkeepBase: 0.04,
    unique: false,
    notes: ["Food output", "Farmer slots", "Base output increased in early-game balance pass"],
  },
  lumberMill: {
    name: "Lumber Mill",
    role: "wood_production",
    description: "Base Wood and Woodcutter slots.",
    unlock: "wood >= 8 or already built",
    cost: { wood: 28, stone: 14, food: 10 },
    slots: 2,
    upkeepBase: 0.05,
    unique: false,
    notes: ["Wood output", "Woodcutter slots"],
  },
  quarry: {
    name: "Quarry",
    role: "stone_production",
    description: "Base Stone and Miner slots.",
    unlock: "farm built or already built",
    cost: { wood: 30, stone: 18, food: 12 },
    slots: 2,
    upkeepBase: 0.05,
    unique: false,
    notes: ["Stone output", "Miner slots"],
  },
  granary: {
    name: "Granary",
    role: "food_storage",
    description: "Safer food storage for hard seasons.",
    unlock: "Food Preservation",
    cost: { wood: 26, stone: 12, food: 12 },
    slots: 0,
    upkeepBase: 0.03,
    unique: true,
    notes: ["Food storage", "Safety buffer"],
  },
  chickenCoop: {
    name: "Chicken Coop",
    role: "food_support",
    description: "A steady trickle of eggs and meat.",
    unlock: "Animal Husbandry",
    cost: { wood: 24, stone: 8, food: 14 },
    slots: 0,
    upkeepBase: 0.03,
    unique: false,
    notes: ["Passive Food"],
  },
  workshop: {
    name: "Workshop",
    role: "production_support",
    description: "Organizes tools and craft.",
    unlock: "Craftsmanship",
    cost: { wood: 32, stone: 18, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    notes: ["Building base output bonus"],
  },
  scribeHall: {
    name: "Scribe Hall",
    role: "knowledge_production",
    description: "A quiet place where Scholars turn records into Knowledge.",
    unlock: "Food Preservation",
    cost: { wood: 28, stone: 18, food: 10 },
    slots: 2,
    upkeepBase: 0.03,
    unique: true,
    notes: ["Knowledge output", "Scholar slots", "Earlier progression"],
  },
  barracks: {
    name: "Barracks",
    role: "military_unlock",
    description: "Unlocks Soldiers and Guards.",
    unlock: "quarry built or already built",
    cost: { wood: 36, stone: 24, food: 16 },
    slots: 0,
    upkeepBase: 0.08,
    unique: true,
    notes: ["Soldiers", "Guards", "Defense layer"],
  },
  warehouse: {
    name: "Warehouse",
    role: "storage_support",
    description: "Large storage increase.",
    unlock: "Storehouse Planning",
    cost: { wood: 40, stone: 26, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    notes: ["Large storage boost"],
  },
  goldMine: {
    name: "Gold Mine",
    role: "gold_production",
    description: "Gold and Miner slots.",
    unlock: "Gold Mining",
    cost: { wood: 52, stone: 38, food: 24 },
    slots: 2,
    upkeepBase: 0.07,
    unique: false,
    notes: ["Gold output", "Miner slots"],
  },
};
