window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.buildings = {
  townHall: {
    name: "Town Hall",
    role: "population_core",
    description: "The heart of your settlement and its population limit.",
    unlock: "start",
    cost: { wood: 64, stone: 42, food: 20 },
    slots: 0,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 30,
    notes: ["Population cap", "Growth support", "Village rank", "Main progression spine"],
  },
  farm: {
    name: "Farm",
    role: "food_production",
    description: "Base Food and Farmer capacity.",
    unlock: "start",
    cost: { wood: 20, stone: 10, food: 8 },
    slots: 4,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Food output", "Farmer capacity", "Base output increased in early-game balance pass"],
  },
  lumberMill: {
    name: "Lumber Mill",
    role: "wood_production",
    description: "Base Wood and Woodcutter capacity.",
    unlock: "wood >= 8 or already built",
    cost: { wood: 28, stone: 14, food: 10 },
    slots: 3,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Wood output", "Woodcutter capacity"],
  },
  quarry: {
    name: "Quarry",
    role: "stone_production",
    description: "Base Stone and Quarry Miner capacity.",
    unlock: "farm built or already built",
    cost: { wood: 30, stone: 18, food: 12 },
    slots: 3,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Stone output", "Quarry Miner capacity"],
  },
  workshop: {
    name: "Workshop",
    role: "production_support",
    description: "Organizes tools and craft.",
    unlock: "Craftsmanship",
    cost: { wood: 32, stone: 18, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Building base output bonus"],
  },
  scribeHall: {
    name: "Scribe Hall",
    role: "knowledge_production",
    description: "A quiet place where Scholars turn records into Knowledge.",
    unlock: "Gold Mining + Town Hall Lv4",
    cost: { wood: 28, stone: 18, food: 10 },
    slots: 1,
    upkeepBase: 0.03,
    unique: true,
    maxLevel: 50,
    townHallLevel: 4,
    notes: ["Knowledge output", "Scholar capacity", "Now appears only after Gold Mining is online"],
  },
  barracks: {
    name: "Barracks",
    role: "military_unlock",
    description: "Unlocks Soldiers and Guards.",
    unlock: "quarry built or already built",
    townHallLevel: 4,
    cost: { wood: 36, stone: 24, food: 16 },
    slots: 0,
    upkeepBase: 0.08,
    unique: true,
    maxLevel: 50,
    notes: ["Soldiers", "Guards", "Defense layer"],
  },
  warehouse: {
    name: "Warehouse",
    role: "storage_support",
    description: "Large storage increase with milestone scaling.",
    unlock: "Storehouse Planning",
    townHallLevel: 2,
    cost: { wood: 40, stone: 26, food: 14 },
    slots: 0,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Global storage boost", "Uses the stronger warehouseBonus curve", "Available earlier to prevent storage deadlocks"],
  },
  goldMine: {
    name: "Gold Mine",
    role: "gold_production",
    description: "Gold and Gold Miner capacity.",
    unlock: "Gold Mining",
    townHallLevel: 5,
    cost: { wood: 52, stone: 38, food: 24 },
    slots: 2,
    upkeepBase: 0.07,
    unique: true,
    maxLevel: 50,
    notes: ["Gold output", "Gold Miner capacity"],
  },
  vineyard: {
    name: "Vineyard",
    role: "luxury_production",
    description: "Terraced vines for later luxuries.",
    unlock: "Viticulture",
    townHallLevel: 10,
    cost: { wood: 42, stone: 22, food: 24 },
    slots: 2,
    upkeepBase: 0.04,
    unique: true,
    maxLevel: 50,
    notes: ["Wine output", "Vinekeeper capacity", "Supports Happiness"],
  },
  winery: {
    name: "Winery",
    role: "luxury_refinement",
    description: "Presses, stores and improves local wine.",
    unlock: "Vintage Press",
    townHallLevel: 12,
    cost: { wood: 56, stone: 30, food: 22 },
    slots: 2,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Wine throughput", "Vintner capacity"],
  },
  oreMine: {
    name: "Ore Pit",
    role: "ore_production",
    description: "A deep excavation for raw ore.",
    unlock: "Ore Extraction",
    townHallLevel: 12,
    cost: { wood: 58, stone: 42, food: 28 },
    slots: 2,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 50,
    notes: ["Ore output", "Ore Miner capacity"],
  },
  smelter: {
    name: "Smelter",
    role: "metal_production",
    description: "Refines ore into usable metal.",
    unlock: "Smithing",
    townHallLevel: 14,
    cost: { wood: 64, stone: 46, food: 26, gold: 8 },
    slots: 2,
    upkeepBase: 0.06,
    unique: true,
    maxLevel: 50,
    notes: ["Metal output", "Consumes Ore", "Smelter capacity"],
  },
  tavern: {
    name: "Tavern",
    role: "happiness_support",
    description: "Keeps spirits high with warm rooms and wine.",
    unlock: "Tavern Culture",
    townHallLevel: 15,
    cost: { wood: 60, stone: 34, food: 26, gold: 10 },
    slots: 2,
    upkeepBase: 0.05,
    unique: true,
    maxLevel: 50,
    notes: ["Happiness support", "Consumes Wine", "Innkeeper capacity"],
  },
};
