window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.techBranches = [
  {
    id: "growth",
    title: "Sustenance",
    hint: "Fields, rations, and resilient village growth.",
  },
  {
    id: "craft",
    title: "Craftsmanship",
    hint: "Timber discipline, workshops, and practical output gains.",
  },
  {
    id: "stone",
    title: "Masonry",
    hint: "Stonework, warehousing, and structural efficiency.",
  },
  {
    id: "civic",
    title: "Scholarship",
    hint: "Records, planning, wine culture, and civic order.",
  },
  {
    id: "military",
    title: "Warfare",
    hint: "Defense, expeditions, and better campaign control.",
  },
  {
    id: "trade",
    title: "Commerce",
    hint: "Coin, trade, ore, and later metal industry.",
  },
];

window.CoinvaleReference.techTreeUi = {
  compactLayout: true,
  showFutureNodes: true,
  detailMode: "hover_tooltip",
};

window.CoinvaleReference.techTreeCosts = {
  predictable: true,
  rule: "Node cost is fixed by its own place in the tree, not by how many sibling nodes were researched first. Deeper nodes are still intentionally more expensive.",
};

window.CoinvaleReference.techTree = {
  fieldRotation: {
    name: "Field Rotation",
    description: "Unlocks the first true farm discipline. Farm output +2%.",
    cost: { food: 18, wood: 12, stone: 6 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.02 }],
    unlocks: ["Early farm output bonus"],
    requires: [],
  },
  betterAgriculture: {
    name: "Better Agriculture",
    description: "Farm output +3%.",
    cost: { food: 28, wood: 14, stone: 10 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.03 }],
    unlocks: ["Food output bonus"],
    requires: ["fieldRotation"],
  },
  seedSelection: {
    name: "Seed Selection",
    description: "Food output +2%.",
    cost: { food: 36, wood: 16, stone: 12 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.02 }],
    unlocks: ["Food output bonus"],
    requires: ["betterAgriculture"],
  },
  irrigation: {
    name: "Irrigation",
    description: "Food output +2%.",
    cost: { food: 46, wood: 22, stone: 18 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.02 }],
    unlocks: ["Food output bonus"],
    requires: ["seedSelection"],
  },
  villageRations: {
    name: "Village Rations",
    description: "Population food upkeep -8%.",
    cost: { food: 74, wood: 28, stone: 26 },
    branch: "growth",
    effects: [{ type: "population_food_upkeep_mult", value: 0.92 }],
    unlocks: ["Lower food upkeep"],
    requires: ["betterAgriculture"],
  },
  communalKitchens: {
    name: "Communal Kitchens",
    description: "Growth stays steadier during lean periods.",
    cost: { food: 82, wood: 32, stone: 22 },
    branch: "growth",
    unlocks: ["Growth stability"],
    requires: ["villageRations"],
  },
  herbalRemedies: {
    name: "Herbal Remedies",
    description: "Growth support +6% and slightly lower food upkeep.",
    cost: { food: 70, wood: 24, stone: 20 },
    branch: "growth",
    effects: [{ type: "population_food_upkeep_mult", value: 0.95 }],
    unlocks: ["Better health and growth"],
    requires: ["communalKitchens"],
  },
  cropRotation: {
    name: "Crop Rotation",
    description: "Food output +2%.",
    cost: { food: 58, wood: 28, stone: 22 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.02 }],
    unlocks: ["Stronger farm scaling"],
    requires: ["irrigation", "herbalRemedies"],
  },
  reinforcedAxes: {
    name: "Reinforced Axes",
    description: "Wood production +3%.",
    cost: { food: 18, wood: 16, stone: 8 },
    branch: "craft",
    effects: [{ type: "production_mult", resource: "wood", value: 1.03 }],
    unlocks: ["Wood output bonus"],
    requires: [],
  },
  craftsmanship: {
    name: "Craftsmanship",
    description: "Unlocks the Workshop.",
    cost: { food: 30, wood: 28, stone: 16 },
    branch: "craft",
    unlocks: ["Workshop"],
    requires: ["reinforcedAxes"],
  },
  sawPits: {
    name: "Saw Pits",
    description: "Wood production +2%.",
    cost: { food: 34, wood: 26, stone: 14 },
    branch: "craft",
    effects: [{ type: "production_mult", resource: "wood", value: 1.02 }],
    unlocks: ["Wood output bonus"],
    requires: ["craftsmanship"],
  },
  timberSeasoning: {
    name: "Timber Seasoning",
    description: "Wood production +1%.",
    cost: { food: 46, wood: 34, stone: 18 },
    branch: "craft",
    effects: [{ type: "production_mult", resource: "wood", value: 1.01 }],
    unlocks: ["Wood output bonus"],
    requires: ["sawPits"],
  },
  storehousePlanning: {
    name: "Storehouse Planning",
    description: "Unlocks the Warehouse.",
    cost: { food: 46, wood: 34, stone: 22 },
    branch: "stone",
    unlocks: ["Warehouse"],
    requires: ["stonecutting"],
  },
  stonecutting: {
    name: "Stonecutting",
    description: "Stone production +3%.",
    cost: { food: 24, wood: 18, stone: 18 },
    branch: "stone",
    effects: [{ type: "production_mult", resource: "stone", value: 1.03 }],
    unlocks: ["Stone output bonus"],
    requires: ["fieldRotation"],
  },
  quarrySupports: {
    name: "Quarry Supports",
    description: "Stone production +2%.",
    cost: { food: 38, wood: 26, stone: 28 },
    branch: "stone",
    effects: [{ type: "production_mult", resource: "stone", value: 1.02 }],
    unlocks: ["Stone output bonus"],
    requires: ["stonecutting"],
  },
  masonry: {
    name: "Masonry",
    description: "Building Wood upkeep -10%.",
    cost: { food: 64, wood: 34, stone: 48 },
    branch: "stone",
    effects: [{ type: "building_wood_upkeep_mult", value: 0.9 }],
    unlocks: ["Lower wood upkeep on buildings"],
    requires: ["quarrySupports"],
  },
  improvedWarehousing: {
    name: "Improved Warehousing",
    description: "Storage capacity +12%.",
    cost: { food: 82, wood: 50, stone: 40 },
    branch: "stone",
    effects: [{ type: "storage_mult", value: 1.12 }],
    unlocks: ["Storage bonus"],
    requires: ["storehousePlanning", "masonry"],
  },
  measuredMasonry: {
    name: "Measured Masonry",
    description: "Building Stone cost -2%.",
    cost: { food: 72, wood: 42, stone: 52 },
    branch: "stone",
    effects: [{ type: "build_cost_mult", resource: "stone", value: 0.98 }],
    unlocks: ["Building Stone cost -2%"],
    requires: ["masonry"],
  },
  pavedYards: {
    name: "Paved Yards",
    description: "Expedition provisions cost -12%.",
    cost: { food: 88, wood: 60, stone: 74 },
    branch: "stone",
    unlocks: ["Lower expedition provisions"],
    requires: ["improvedWarehousing"],
  },
  recordKeeping: {
    name: "Record Keeping",
    description: "Knowledge output +6%.",
    cost: { food: 30, wood: 20, stone: 14 },
    branch: "civic",
    effects: [{ type: "worker_output_mult", worker: "scholars", value: 1.06 }],
    unlocks: ["Knowledge bonus"],
    requires: [],
  },
  scriptoriums: {
    name: "Scriptoriums",
    description: "Formal study improves Knowledge output +8%.",
    cost: { food: 46, wood: 30, stone: 18 },
    branch: "civic",
    effects: [{ type: "worker_output_mult", worker: "scholars", value: 1.08 }],
    unlocks: ["Scholar bonus"],
    requires: ["recordKeeping"],
  },
  planningOffice: {
    name: "Planning Office",
    description: "Building Wood cost -2%.",
    cost: { food: 84, wood: 54, stone: 34 },
    branch: "civic",
    effects: [{ type: "build_cost_mult", resource: "wood", value: 0.98 }],
    unlocks: ["Building Wood cost -2%"],
    requires: ["scriptoriums", "masonry"],
  },
  viticulture: {
    name: "Viticulture",
    description: "Unlocks the Vineyard and local wine.",
    cost: { food: 110, wood: 56, stone: 44 },
    branch: "civic",
    unlocks: ["Vineyard", "Wine economy"],
    requires: ["scriptoriums", "improvedWarehousing"],
    townHallLevel: 10,
  },
  villageCustoms: {
    name: "Village Customs",
    description: "Unlocks the first civic happiness layer once wine exists.",
    cost: { food: 126, wood: 58, stone: 42 },
    branch: "civic",
    unlocks: ["First wine-backed civic happiness layer"],
    requires: ["viticulture"],
  },
  festivals: {
    name: "Festivals",
    description: "Happiness gains from wine and village life improve.",
    cost: { food: 148, wood: 72, stone: 58, gold: 20 },
    branch: "civic",
    unlocks: ["Happiness bonus"],
    requires: ["villageCustoms"],
  },
  vintagePress: {
    name: "Vintage Press",
    description: "Unlocks the Winery and improves wine output.",
    cost: { food: 148, wood: 72, stone: 58, gold: 28 },
    branch: "civic",
    effects: [{ type: "production_mult", resource: "wine", value: 1.1 }],
    unlocks: ["Winery"],
    requires: ["viticulture"],
  },
  tavernCulture: {
    name: "Tavern Culture",
    description: "Unlocks the Tavern and wine-fed happiness.",
    cost: { food: 186, wood: 88, stone: 72, gold: 48 },
    branch: "civic",
    unlocks: ["Tavern", "Wine-fed happiness"],
    requires: ["vintagePress", "festivals"],
  },
  militaryDrills: {
    name: "Military Drills",
    description: "Expedition success +12%.",
    cost: { food: 34, wood: 34, stone: 28 },
    branch: "military",
    unlocks: ["Expedition success bonus"],
    requires: ["stonecutting"],
  },
  watchfires: {
    name: "Watchfires",
    description: "Expedition success +8% and better guard support.",
    cost: { food: 58, wood: 54, stone: 24 },
    branch: "military",
    unlocks: ["Expedition success", "Guard support"],
    requires: ["militaryDrills"],
  },
  fieldMedicine: {
    name: "Field Medicine",
    description: "Expedition losses are lighter on failure.",
    cost: { food: 74, wood: 34, stone: 32 },
    branch: "military",
    unlocks: ["Less expedition attrition"],
    requires: ["watchfires"],
  },
  logistics: {
    name: "Logistics",
    description: "Expedition duration -12%.",
    cost: { food: 82, wood: 48, stone: 38 },
    branch: "military",
    unlocks: ["Shorter expeditions"],
    requires: ["fieldMedicine"],
  },
  fortifiedPatrols: {
    name: "Fortified Patrols",
    description: "Guard and Soldier food upkeep -18%.",
    cost: { food: 96, wood: 64, stone: 52 },
    branch: "military",
    effects: [{ type: "worker_upkeep_mult", worker: "soldiers", value: 0.82 }, { type: "worker_upkeep_mult", worker: "guards", value: 0.86 }],
    unlocks: ["Lower guard and soldier upkeep"],
    requires: ["logistics"],
  },
  fortifiedStoreyards: {
    name: "Fortified Storeyards",
    description: "Counter-raids steal fewer supplies.",
    cost: { food: 128, wood: 86, stone: 74, gold: 34 },
    branch: "military",
    unlocks: ["Lower raid losses"],
    requires: ["fortifiedPatrols", "improvedWarehousing"],
  },
  goldMining: {
    name: "Gold Mining",
    description: "Unlocks Gold and Gold Mines.",
    cost: { food: 84, wood: 82, stone: 68 },
    branch: "trade",
    unlocks: ["Gold Mine", "Gold economy"],
    requires: ["stonecutting", "craftsmanship"],
    townHallLevel: 4,
  },
  coinMinting: {
    name: "Coin Minting",
    description: "Gold output +4%.",
    cost: { food: 76, wood: 42, stone: 28, gold: 18 },
    branch: "trade",
    effects: [{ type: "production_mult", resource: "gold", value: 1.04 }],
    unlocks: ["Gold output bonus"],
    requires: ["goldMining"],
  },
  tradeCaravans: {
    name: "Trade Caravans",
    description: "Traders appear more often.",
    cost: { food: 110, wood: 62, stone: 36, gold: 42 },
    branch: "trade",
    unlocks: ["Better trade flow"],
    requires: ["coinMinting"],
  },
  taxLedgers: {
    name: "Tax Ledgers",
    description: "Town Hall yields a trickle of Gold.",
    cost: { food: 126, wood: 72, stone: 44, gold: 56 },
    branch: "trade",
    effects: [{ type: "production_per_town_hall_level", resource: "gold", value: 0.016, requiresTech: "goldMining" }],
    unlocks: ["Town Hall gold trickle"],
    requires: ["tradeCaravans"],
  },
  deepShafts: {
    name: "Deep Shafts",
    description: "Gold output +3%.",
    cost: { food: 108, wood: 62, stone: 66, gold: 44 },
    branch: "trade",
    effects: [{ type: "production_mult", resource: "gold", value: 1.03 }],
    unlocks: ["Gold output bonus"],
    requires: ["goldMining", "masonry"],
  },
  oreExtraction: {
    name: "Ore Extraction",
    description: "Unlocks the Ore Pit.",
    cost: { food: 168, wood: 96, stone: 102, gold: 88 },
    branch: "trade",
    effects: [{ type: "worker_output_mult", worker: "oreMiners", value: 1.08 }],
    unlocks: ["Ore Pit"],
    requires: ["deepShafts"],
    townHallLevel: 10,
  },
  smithing: {
    name: "Smithing",
    description: "Unlocks the Smelter and refined metal.",
    cost: { food: 188, wood: 106, stone: 118, gold: 112 },
    branch: "trade",
    effects: [{ type: "worker_output_mult", worker: "smelters", value: 1.08 }],
    unlocks: ["Smelter", "Metal economy"],
    requires: ["oreExtraction"],
    townHallLevel: 12,
  },
  marketCharters: {
    name: "Market Charters",
    description: "Trader deals pay out +12%.",
    cost: { food: 214, wood: 120, stone: 84, gold: 136 },
    branch: "trade",
    unlocks: ["Later trade scaling"],
    requires: ["smithing"],
  },
  harvestMastery: {
    name: "Harvest Mastery",
    description: "Endless refinement of the fields. Food production +1% per level.",
    cost: { food: 0 },
    branch: "growth",
    effects: [{ type: "production_mult", resource: "food", value: 1.01, perLevel: true }],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable food bonus"],
    requires: ["cropRotation"],
  },
  timberMastery: {
    name: "Timber Mastery",
    description: "Generations of forestry craft. Wood production +1% per level.",
    cost: { wood: 0 },
    branch: "craft",
    effects: [{ type: "production_mult", resource: "wood", value: 1.01, perLevel: true }],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable wood bonus"],
    requires: ["timberSeasoning"],
  },
  masonsMastery: {
    name: "Mason's Mastery",
    description: "Stonework raised to an art. Stone production +1% per level.",
    cost: { stone: 0 },
    branch: "stone",
    effects: [{ type: "production_mult", resource: "stone", value: 1.01, perLevel: true }],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable stone bonus"],
    requires: ["pavedYards"],
  },
  cellarMastery: {
    name: "Cellar Mastery",
    description: "Deep cellars and patient casks. Wine production +1% per level.",
    cost: { food: 0 },
    branch: "civic",
    effects: [{ type: "production_mult", resource: "wine", value: 1.01, perLevel: true }],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable wine bonus"],
    requires: ["tavernCulture"],
  },
  drillMastery: {
    name: "Drill Mastery",
    description: "Discipline that feeds itself. Guard and Soldier food upkeep -0.5% per level.",
    cost: { food: 0 },
    branch: "military",
    effects: [
      { type: "worker_upkeep_mult", worker: "guards", value: 0.995, perLevel: true },
      { type: "worker_upkeep_mult", worker: "soldiers", value: 0.995, perLevel: true }
    ],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable military upkeep reduction"],
    requires: ["fortifiedStoreyards"],
  },
  coinMastery: {
    name: "Coin Mastery",
    description: "Ledgers, levies, and sharper deals. Gold production +1% per level.",
    cost: { gold: 0 },
    branch: "trade",
    effects: [{ type: "production_mult", resource: "gold", value: 1.01, perLevel: true }],
    repeatable: { maxLevel: 100, cost: { base: 40, perLevel: 10 } },
    unlocks: ["Repeatable gold bonus"],
    requires: ["marketCharters"],
  },
};


if (typeof module !== "undefined") {
  module.exports = {
    techBranches: window.CoinvaleReference.techBranches,
    techTree: window.CoinvaleReference.techTree,
    techTreeCosts: window.CoinvaleReference.techTreeCosts,
    techTreeUi: window.CoinvaleReference.techTreeUi,
  };
}