window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.workers = {
  foragers: {
    name: "Forager",
    description: "Gathers berries and roots.",
    role: "starter_food",
    unlock: "start",
    visibility: { type: "always" },
    output: { food: 0.37 },
    upkeep: {},
    slotType: "free",
  },
  woodGatherers: {
    name: "Wood Gatherer",
    description: "Collects rough timber.",
    role: "starter_wood",
    unlock: "start",
    visibility: { type: "always" },
    output: { wood: 0.24 },
    upkeep: {},
    slotType: "free",
  },
  stoneCollectors: {
    name: "Stone Collector",
    description: "Collects loose Stone.",
    role: "starter_stone",
    unlock: "start",
    visibility: { type: "always" },
    output: { stone: 0.16 },
    upkeep: {},
    slotType: "free",
  },
  farmers: {
    name: "Farmer",
    description: "Works the Farm.",
    role: "farm_food",
    unlock: "Farm",
    visibility: { type: "building", building: "farm" },
    building: "farm",
    output: { food: 0.52 },
    upkeep: {},
    slotType: "slot",
  },
  woodcutters: {
    name: "Woodcutter",
    description: "Works the Lumber Mill.",
    role: "mill_wood",
    unlock: "Lumber Mill",
    visibility: { type: "building", building: "lumberMill" },
    building: "lumberMill",
    output: { wood: 0.4 },
    upkeep: {},
    slotType: "slot",
  },
  quarryMiners: {
    name: "Quarry Miner",
    description: "Cuts stone from the Quarry.",
    role: "quarry_stone",
    unlock: "Quarry",
    visibility: { type: "building", building: "quarry" },
    building: "quarry",
    output: { stone: 0.36 },
    upkeep: {},
    slotType: "slot",
  },
  goldMiners: {
    name: "Gold Miner",
    description: "Pulls ore-rich gold from the mine.",
    role: "gold_mining",
    unlock: "Gold Mine + Gold Mining",
    visibility: { type: "buildingAndTech", building: "goldMine", tech: "goldMining" },
    building: "goldMine",
    output: { gold: 0.18 },
    upkeep: {},
    slotType: "slot",
  },
  scholars: {
    name: "Scholar",
    description: "Turns gold-backed study into Knowledge.",
    role: "knowledge",
    unlock: "Scribe Hall + Gold Mining",
    visibility: { type: "buildingAndTech", building: "scribeHall", tech: "goldMining" },
    building: "scribeHall",
    output: { knowledge: 0.14 },
    upkeep: { gold: 0.05 },
    slotType: "slot",
  },
  villagers: {
    name: "Villager",
    description: "Adds a small passive knowledge trickle.",
    role: "passive_knowledge",
    unlock: "start",
    visibility: { type: "always" },
    output: { knowledge: 0.006 },
    upkeep: {},
    slotType: "passive_per_population",
  },
  vinekeepers: {
    name: "Vinekeeper",
    description: "Tends vines and gathers grapes.",
    role: "vineyard",
    unlock: "Vineyard + Viticulture",
    visibility: { type: "buildingAndTech", building: "vineyard", tech: "viticulture" },
    building: "vineyard",
    output: { wine: 0.16 },
    upkeep: {},
    slotType: "slot",
  },
  oreMiners: {
    name: "Ore Miner",
    description: "Extracts ore from the pit.",
    role: "ore_mining",
    unlock: "Ore Pit + Ore Extraction",
    visibility: { type: "buildingAndTech", building: "oreMine", tech: "oreExtraction" },
    building: "oreMine",
    output: { ore: 0.22 },
    upkeep: {},
    slotType: "slot",
  },
  smelters: {
    name: "Smelter",
    description: "Refines ore into usable metal.",
    role: "metalwork",
    unlock: "Smelter + Smithing",
    visibility: { type: "buildingAndTech", building: "smelter", tech: "smithing" },
    building: "smelter",
    output: { metal: 0.14 },
    upkeep: { ore: 0.18 },
    slotType: "slot",
  },
  vintners: {
    name: "Vintner",
    description: "Presses and ages wine from grapes and stores.",
    role: "wine_refinement",
    unlock: "Winery + Vintage Press",
    visibility: { type: "buildingAndTech", building: "winery", tech: "vintagePress" },
    building: "winery",
    output: { wine: 0.1 },
    upkeep: {},
    slotType: "slot",
  },
  innkeepers: {
    name: "Innkeeper",
    description: "Keeps the tavern lively and keeps villagers content.",
    role: "happiness_service",
    unlock: "Tavern + Tavern Culture",
    visibility: { type: "buildingAndTech", building: "tavern", tech: "tavernCulture" },
    building: "tavern",
    output: {},
    upkeep: { wine: 0.08 },
    slotType: "slot",
  },
  guards: {
    name: "Guard",
    description: "Keeps watch and helps blunt counter-raids.",
    role: "village_defense",
    unlock: "Barracks",
    visibility: { type: "building", building: "barracks" },
    output: {},
    upkeep: { food: 0.2 },
    slotType: "free",
  },
  soldiers: {
    name: "Soldier",
    description: "Protects the village and leads expeditions.",
    role: "expeditions",
    unlock: "Barracks",
    visibility: { type: "building", building: "barracks" },
    output: {},
    upkeep: { food: 0.26 },
    slotType: "free",
  },
};

if (typeof module !== "undefined") {
  module.exports = { workers: window.CoinvaleReference.workers };
}
