window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.workers = {
  foragers: {
    name: "Forager",
    role: "starter_food",
    unlock: "start",
    output: { food: 0.37 },
    upkeep: {},
    slotType: "free",
  },
  woodGatherers: {
    name: "Wood Gatherer",
    role: "starter_wood",
    unlock: "start",
    output: { wood: 0.26 },
    upkeep: {},
    slotType: "free",
  },
  stoneCollectors: {
    name: "Stone Collector",
    role: "starter_stone",
    unlock: "start",
    output: { stone: 0.18 },
    upkeep: {},
    slotType: "free",
  },
  farmers: {
    name: "Farmer",
    role: "farm_food",
    unlock: "Farm",
    output: { food: 0.72 },
    upkeep: {},
    slotType: "slot",
  },
  woodcutters: {
    name: "Woodcutter",
    role: "mill_wood",
    unlock: "Lumber Mill",
    output: { wood: 0.66 },
    upkeep: {},
    slotType: "slot",
  },
  miners: {
    name: "Miner",
    role: "quarry_and_gold",
    unlock: "Quarry or Gold Mine",
    output: { stone: 0.62, gold: 0.24 },
    upkeep: {},
    slotType: "slot",
  },
  scholars: {
    name: "Scholar",
    role: "knowledge",
    unlock: "Scribe Hall",
    output: { knowledge: 0.2 },
    upkeep: { gold: 0.06 },
    slotType: "slot",
  },
  villagers: {
    name: "Villager",
    role: "passive_knowledge",
    unlock: "start",
    output: { knowledge: 0.01 },
    upkeep: {},
    slotType: "passive_per_population",
  },
  guards: {
    name: "Guard",
    role: "village_defense",
    unlock: "Barracks",
    output: {},
    upkeep: { food: 0.18 },
    slotType: "free",
  },
  soldiers: {
    name: "Soldier",
    role: "expeditions",
    unlock: "Barracks",
    output: {},
    upkeep: { food: 0.22 },
    slotType: "free",
  },
};
