window.CoinvaleReference = window.CoinvaleReference || {};

window.CoinvaleReference.workers = {
  foragers: {
    name: "Forager",
    role: "starter_food",
    unlock: "start",
    output: { food: 0.37 },
    upkeep: {},
    slotType: "free",
  },
  woodGatherers: {
    name: "Wood Gatherer",
    role: "starter_wood",
    unlock: "start",
    output: { wood: 0.24 },
    upkeep: {},
    slotType: "free",
  },
  stoneCollectors: {
    name: "Stone Collector",
    role: "starter_stone",
    unlock: "start",
    output: { stone: 0.16 },
    upkeep: {},
    slotType: "free",
  },
  farmers: {
    name: "Farmer",
    role: "farm_food",
    unlock: "Farm",
    output: { food: 0.52 },
    upkeep: {},
    slotType: "slot",
  },
  woodcutters: {
    name: "Woodcutter",
    role: "mill_wood",
    unlock: "Lumber Mill",
    output: { wood: 0.4 },
    upkeep: {},
    slotType: "slot",
  },
  quarryMiners: {
    name: "Quarry Miner",
    role: "quarry_stone",
    unlock: "Quarry",
    output: { stone: 0.36 },
    upkeep: {},
    slotType: "slot",
  },
  goldMiners: {
    name: "Gold Miner",
    role: "gold_mining",
    unlock: "Gold Mine + Gold Mining",
    output: { gold: 0.18 },
    upkeep: {},
    slotType: "slot",
  },
  scholars: {
    name: "Scholar",
    role: "knowledge",
    unlock: "Scribe Hall + Gold Mining",
    output: { knowledge: 0.14 },
    upkeep: { gold: 0.05 },
    slotType: "slot",
  },
  villagers: {
    name: "Villager",
    role: "passive_knowledge",
    unlock: "start",
    output: { knowledge: 0.006 },
    upkeep: {},
    slotType: "passive_per_population",
  },
  vinekeepers: {
    name: "Vinekeeper",
    role: "vineyard",
    unlock: "Vineyard + Viticulture",
    output: { wine: 0.16 },
    upkeep: {},
    slotType: "slot",
  },
  oreMiners: {
    name: "Ore Miner",
    role: "ore_mining",
    unlock: "Ore Pit + Ore Extraction",
    output: { ore: 0.22 },
    upkeep: {},
    slotType: "slot",
  },
  smelters: {
    name: "Smelter",
    role: "metalwork",
    unlock: "Smelter + Smithing",
    output: { metal: 0.14 },
    upkeep: { ore: 0.18 },
    slotType: "slot",
  },
  vintners: {
    name: "Vintner",
    role: "wine_refinement",
    unlock: "Winery + Vintage Press",
    output: { wine: 0.1 },
    upkeep: {},
    slotType: "slot",
  },
  innkeepers: {
    name: "Innkeeper",
    role: "happiness_service",
    unlock: "Tavern + Tavern Culture",
    output: {},
    upkeep: { wine: 0.08 },
    slotType: "slot",
  },
  guards: {
    name: "Guard",
    role: "village_defense",
    unlock: "Barracks",
    output: {},
    upkeep: { food: 0.2 },
    slotType: "free",
  },
  soldiers: {
    name: "Soldier",
    role: "expeditions",
    unlock: "Barracks",
    output: {},
    upkeep: { food: 0.26 },
    slotType: "free",
  },
};
